import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import CodeMirror from "@uiw/react-codemirror";
import { htmlLanguage } from "@codemirror/lang-html";
import Header from "../src/components/header";
import ImportButton from "../src/components/importButton";

export default function Home() {
  const [file, setFile] = useState({});

  const getFileData = (e) => {
    const file = e.target.files[0];
    const reader = new FileReader();

    reader.onload = function (event) {
      setFile({ name: e.target.files[0].name, content: event.target.result });
    };

    reader.readAsText(file);
  };

  return (
    <div>
      <Head>
        <title>Bothive liquid editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <ImportButton getFileData={getFileData} />
      <CodeMirror value={file.content} extensions={htmlLanguage} />
    </div>
  );
}
