import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "../src/components/header";
import ImportButton from "../src/components/importButton";
import CodeMirror from "@uiw/react-codemirror";
import { htmlLanguage } from "@codemirror/lang-html";

export default function Home() {
  const [file, setFile] = useState({});

  const getFileData = (e) => {
    const file = e.target.files[0];
    const reader = new FileReader();

    reader.onload = function (event) {
      setFile({ name: e.target.files[0].name, content: event.target.result });
    };

    reader.readAsText(file);
  };

  return (
    <div>
      <Head>
        <title>Bothive liquid editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <p>Document name</p>
      <p>
        <strong>{file.name}</strong>
      </p>

      <ImportButton getFileData={getFileData} />

      <CodeMirror
        value={file.content}
        extensions={htmlLanguage}
        onChange={(value, viewUpdate) => {
          console.log("value:", value);
        }}
        options={{
          placeholder: "Please enter the JavaScript code.",
          tabSize: 2,
          mode: "js",
        }}
      />
    </div>
  );
}
