import React, { useState } from "react";
import Head from "next/head";
import Header from "../src/components/shared/header";
import { JSONeditor } from "../src/components/json_editor";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bothive Scenario</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <JSONeditor />
    </div>
  );
}
